# Generated by Django 2.0.2 on 2018-04-04 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('gain_lose_maintain', models.IntegerField(default=3)),
                ('cell', models.CharField(default='', max_length=12)),
                ('breakTime', models.TimeField(blank=True, null=True)),
                ('lunchTime', models.TimeField(blank=True, null=True)),
                ('dinnerTime', models.TimeField(blank=True, null=True)),
                ('dietRestrict', models.CharField(default='', max_length=100)),
                ('allergies', models.CharField(default='', max_length=100)),
                ('prefDict', models.CharField(default='', max_length=2048)),
                ('mealDict', models.CharField(default='', max_length=2048)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
