# Generated by Django 2.0.2 on 2018-04-05 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('gain_lose_maintain', models.IntegerField(default=3)),
                ('cell', models.CharField(default='', max_length=12)),
                ('breakTime', models.TimeField(blank=True, null=True)),
                ('lunchTime', models.TimeField(blank=True, null=True)),
                ('dinnerTime', models.TimeField(blank=True, null=True)),
                ('dietRestrict', models.CharField(default='', max_length=100)),
                ('allergies', models.CharField(default='', max_length=100)),
                ('prefDict', models.CharField(default='', max_length=10000)),
                ('mealDict', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
