# Generated by Django 2.0.2 on 2018-04-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mealDict',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='prefDict',
            field=models.TextField(default=''),
        ),
    ]
