# Generated by Django 2.0.2 on 2018-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='prefDict',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
