# Generated by Django 2.0.2 on 2018-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cell',
            field=models.CharField(default='', max_length=12),
        ),
    ]
