# Generated by Django 2.0.2 on 2018-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_preference',
            name='breakTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='dinnerTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_preference',
            name='lunchTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
