# Generated by Django 2.0.2 on 2018-04-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_prefdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mealDict',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
