# Generated by Django 2.0.2 on 2018-04-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180404_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='activity_level',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mf',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
