# Generated by Django 2.0.2 on 2018-04-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo_mealdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_meals',
            name='userId',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='allergies',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dietRestrict',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gain_lose_maintain',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='User_Meals',
        ),
    ]
