from ..Forms.forms import PreferencesForm

def createPreferences(form):
    proteinDict = {
        'chicken' : form.__dict__['data']['chicken'],
        'steak' : form.__dict__['data']['steak'],
        'beef' : form.__dict__['data']['beef'],
        'pork' : form.__dict__['data']['pork'],
        'bacon' : form.__dict__['data']['bacon'],
        'sausage' : form.__dict__['data']['sausage'],
        'ham' : form.__dict__['data']['ham'],
        'turkey' : form.__dict__['data']['turkey'],
        'lamb' : form.__dict__['data']['lamb'],
        'eggs' : form.__dict__['data']['eggs'],
        'beans' : form.__dict__['data']['beans'],
        'tofu' : form.__dict__['data']['tofu'],
        'fish' : form.__dict__['data']['fish'],
        'salmon' : form.__dict__['data']['salmon'],
        'tilapia' : form.__dict__['data']['tilapia'],
        'tuna' : form.__dict__['data']['tuna']
    }
    carbDict = {
        'pasta' : form.__dict__['data']['pasta'],
        'bread' : form.__dict__['data']['bread'],
        'rice' : form.__dict__['data']['rice'],
        'quinoa' : form.__dict__['data']['quinoa'],
        'whole_grain' : form.__dict__['data']['whole_grain'],
        'whole_wheat' : form.__dict__['data']['whole_wheat'],
        'tortilla' : form.__dict__['data']['tortilla'],
        'oat' : form.__dict__['data']['oat'],
        'cereal' : form.__dict__['data']['cereal'],
        'pita' : form.__dict__['data']['pita']
    }
    fruitDict = {
        'banana' : form.__dict__['data']['banana'],
        'strawberry' : form.__dict__['data']['strawberry'],
        'raspberry' : form.__dict__['data']['raspberry'],
        'blueberry' : form.__dict__['data']['blueberry'],
        'cantelope' : form.__dict__['data']['cantelope'],
        'pineapple' : form.__dict__['data']['pineapple'],
        'coconut' : form.__dict__['data']['coconut'],
        'grape' : form.__dict__['data']['grape'],
        'mango' : form.__dict__['data']['mango'],
        'pear' : form.__dict__['data']['pear'],
        'plum' : form.__dict__['data']['plum'],
        'peach' : form.__dict__['data']['peach'],
        'watermelon' : form.__dict__['data']['watermelon'],
        'apple' : form.__dict__['data']['apple'],
        'orange' : form.__dict__['data']['orange'],
        'lemon' : form.__dict__['data']['lemon'],
        'lime' : form.__dict__['data']['lime']
    }
    vegetableDict = {
        'carrot' : form.__dict__['data']['carrot'],
        'squash' : form.__dict__['data']['squash'],
        'cucumber' : form.__dict__['data']['cucumber'],
        'bell_pepper' : form.__dict__['data']['bell_pepper'],
        'onion' : form.__dict__['data']['onion'],
        'celery' : form.__dict__['data']['celery'],
        'tomato' : form.__dict__['data']['tomato'],
        'potato' : form.__dict__['data']['potato'],
        'broccoli' : form.__dict__['data']['broccoli'],
        'corn' : form.__dict__['data']['corn'],
        'mushroom' : form.__dict__['data']['mushroom'],
        'lettuce' : form.__dict__['data']['lettuce'],
        'spinach' : form.__dict__['data']['spinach'],
        'kale' : form.__dict__['data']['kale'],
        'sweet_potato' : form.__dict__['data']['sweet_potato'],
        'zucchini' : form.__dict__['data']['zucchini'],
        'asparagus' : form.__dict__['data']['asparagus']
    }
    dairyDict = {
        'milk' : form.__dict__['data']['milk'],
        'yogurt' : form.__dict__['data']['yogurt'],
        'cheese' : form.__dict__['data']['cheese'],
        'american_cheese' : form.__dict__['data']['american_cheese'],
        'mozzerella' : form.__dict__['data']['mozzerella'],
        'provolone' : form.__dict__['data']['provolone'],
        'swiss' : form.__dict__['data']['swiss'],
        'goat_cheese' : form.__dict__['data']['goat_cheese'],
        'blue_cheese' : form.__dict__['data']['blue_cheese'],
        'skim_milk' : form.__dict__['data']['skim_milk'],
        'butter' : form.__dict__['data']['butter']
    }
    spiceDict = {
        'garlic' : form.__dict__['data']['garlic'],
        'chili_powder' : form.__dict__['data']['chili_powder'],
        'cayenne' : form.__dict__['data']['cayenne'],
        'cumin' : form.__dict__['data']['cumin'],
        'ginger' : form.__dict__['data']['ginger'],
        'paprika' : form.__dict__['data']['paprika'],
        'saffron' : form.__dict__['data']['saffron'],
        'cinnamon' : form.__dict__['data']['cinnamon'],
        'curry_powder' : form.__dict__['data']['curry_powder'],
        'tumeric' : form.__dict__['data']['tumeric'],
        'ginger' : form.__dict__['data']['ginger']
    }
    herbDict = {
        'oregano' : form.__dict__['data']['oregano'],
        'cilantro' : form.__dict__['data']['cilantro'],
        'thyme' : form.__dict__['data']['thyme'],
        'basil' : form.__dict__['data']['basil'],
        'parsley' : form.__dict__['data']['parsley'],
        'rosemary' : form.__dict__['data']['rosemary'],
        'mint' : form.__dict__['data']['mint'],
        'sage' : form.__dict__['data']['sage'],
        'bay_leaf' : form.__dict__['data']['bay_leaf']
    }
    prefDict = {
        'proteinDict' : proteinDict,
        'carbDict' : carbDict,
        'fruitDict' : fruitDict,
        'vegetableDict' : vegetableDict,
        'dairyDict' : dairyDict,
        'spiceDict' : spiceDict,
        'herbDict' : herbDict,
    }
    return prefDict

def populatePreferences(request):
    form = PreferencesForm(initial={
    'chicken':request.session['prefDict']['proteinDict']['chicken'],
    'steak':request.session['prefDict']['proteinDict']['steak'],
    'beef':request.session['prefDict']['proteinDict']['beef'],
    'pork':request.session['prefDict']['proteinDict']['pork'],
    'bacon':request.session['prefDict']['proteinDict']['bacon'],
    'sausage':request.session['prefDict']['proteinDict']['sausage'],
    'ham':request.session['prefDict']['proteinDict']['ham'],
    'turkey':request.session['prefDict']['proteinDict']['turkey'],
    'lamb':request.session['prefDict']['proteinDict']['lamb'],
    'eggs':request.session['prefDict']['proteinDict']['eggs'],
    'beans':request.session['prefDict']['proteinDict']['beans'],
    'tofu':request.session['prefDict']['proteinDict']['tofu'],
    'fish':request.session['prefDict']['proteinDict']['fish'],
    'salmon':request.session['prefDict']['proteinDict']['salmon'],
    'tilapia':request.session['prefDict']['proteinDict']['tilapia'],
    'tuna':request.session['prefDict']['proteinDict']['tuna'],

    'pasta':request.session['prefDict']['carbDict']['pasta'],
    'bread':request.session['prefDict']['carbDict']['bread'],
    'rice':request.session['prefDict']['carbDict']['rice'],
    'quinoa':request.session['prefDict']['carbDict']['quinoa'],
    'whole_grain':request.session['prefDict']['carbDict']['whole_grain'],
    'whole_wheat':request.session['prefDict']['carbDict']['whole_wheat'],
    'tortilla':request.session['prefDict']['carbDict']['tortilla'],
    'oat':request.session['prefDict']['carbDict']['oat'],
    'cereal':request.session['prefDict']['carbDict']['cereal'],
    'pita':request.session['prefDict']['carbDict']['pita'],

    'banana':request.session['prefDict']['fruitDict']['banana'],
    'strawberry':request.session['prefDict']['fruitDict']['strawberry'],
    'raspberry':request.session['prefDict']['fruitDict']['raspberry'],
    'blueberry':request.session['prefDict']['fruitDict']['blueberry'],
    'cantelope':request.session['prefDict']['fruitDict']['cantelope'],
    'pineapple':request.session['prefDict']['fruitDict']['pineapple'],
    'coconut':request.session['prefDict']['fruitDict']['coconut'],
    'grape':request.session['prefDict']['fruitDict']['grape'],
    'mango':request.session['prefDict']['fruitDict']['mango'],
    'pear':request.session['prefDict']['fruitDict']['pear'],
    'plum':request.session['prefDict']['fruitDict']['plum'],
    'peach':request.session['prefDict']['fruitDict']['peach'],
    'watermelon':request.session['prefDict']['fruitDict']['watermelon'],
    'apple':request.session['prefDict']['fruitDict']['apple'],
    'orange':request.session['prefDict']['fruitDict']['orange'],
    'lemon':request.session['prefDict']['fruitDict']['lemon'],
    'lime':request.session['prefDict']['fruitDict']['lime'],

    'carrot':request.session['prefDict']['vegetableDict']['carrot'],
    'squash':request.session['prefDict']['vegetableDict']['squash'],
    'cucumber':request.session['prefDict']['vegetableDict']['cucumber'],
    'bell_pepper':request.session['prefDict']['vegetableDict']['bell_pepper'],
    'onion':request.session['prefDict']['vegetableDict']['onion'],
    'celery':request.session['prefDict']['vegetableDict']['celery'],
    'tomato':request.session['prefDict']['vegetableDict']['tomato'],
    'potato':request.session['prefDict']['vegetableDict']['potato'],
    'broccoli':request.session['prefDict']['vegetableDict']['broccoli'],
    'corn':request.session['prefDict']['vegetableDict']['corn'],
    'mushroom':request.session['prefDict']['vegetableDict']['mushroom'],
    'lettuce':request.session['prefDict']['vegetableDict']['lettuce'],
    'spinach':request.session['prefDict']['vegetableDict']['spinach'],
    'kale':request.session['prefDict']['vegetableDict']['kale'],
    'sweet_potato':request.session['prefDict']['vegetableDict']['sweet_potato'],
    'zucchini':request.session['prefDict']['vegetableDict']['zucchini'],
    'asparagus':request.session['prefDict']['vegetableDict']['asparagus'],

    'milk':request.session['prefDict']['dairyDict']['milk'],
    'yogurt':request.session['prefDict']['dairyDict']['yogurt'],
    'cheese':request.session['prefDict']['dairyDict']['cheese'],
    'american_cheese':request.session['prefDict']['dairyDict']['american_cheese'],
    'mozzerella':request.session['prefDict']['dairyDict']['mozzerella'],
    'provolone':request.session['prefDict']['dairyDict']['provolone'],
    'swiss':request.session['prefDict']['dairyDict']['swiss'],
    'goat_cheese':request.session['prefDict']['dairyDict']['goat_cheese'],
    'blue_cheese':request.session['prefDict']['dairyDict']['blue_cheese'],
    'skim_milk':request.session['prefDict']['dairyDict']['skim_milk'],
    'butter':request.session['prefDict']['dairyDict']['butter'],

    'garlic':request.session['prefDict']['spiceDict']['garlic'],
    'chili_powder':request.session['prefDict']['spiceDict']['chili_powder'],
    'cayenne':request.session['prefDict']['spiceDict']['cayenne'],
    'cumin':request.session['prefDict']['spiceDict']['cumin'],
    'ginger':request.session['prefDict']['spiceDict']['ginger'],
    'paprika':request.session['prefDict']['spiceDict']['paprika'],
    'saffron':request.session['prefDict']['spiceDict']['saffron'],
    'cinnamon':request.session['prefDict']['spiceDict']['cinnamon'],
    'curry_powder':request.session['prefDict']['spiceDict']['curry_powder'],
    'tumeric':request.session['prefDict']['spiceDict']['tumeric'],
    'ginger':request.session['prefDict']['spiceDict']['ginger'],

    'oregano':request.session['prefDict']['herbDict']['oregano'],
    'cilantro':request.session['prefDict']['herbDict']['cilantro'],
    'thyme':request.session['prefDict']['herbDict']['thyme'],
    'basil':request.session['prefDict']['herbDict']['basil'],
    'parsley':request.session['prefDict']['herbDict']['parsley'],
    'rosemary':request.session['prefDict']['herbDict']['rosemary'],
    'mint':request.session['prefDict']['herbDict']['mint'],
    'sage':request.session['prefDict']['herbDict']['sage'],
    'bay_leaf':request.session['prefDict']['herbDict']['bay_leaf'],

    })
    return form
